### ISSUE TITLE
Some issues with the replication experiment

### ISSUE THREAD

**Issue by DMoRanSky** [rutgers-db/SeRF#1]
Does your code showing in GitHub now only support the DEEP dataset? It seems that benchmark_deep_xxx can only run in the DEEP dataset.

Also, I want to ask if it seems that I can use " ./benchmark/deep_halfbound  -method <different method name>" to test by using different methods. Can you list all the method names you support now?

**Comment by ciuji** [comment]
We support multiple datasets in different formats. For more supporting reading functions, please check `/src/common/reader.cc`.
The `-method` parameter is for internal use only. The current released code only supports `segment_graph_1d` and `segment_graph_2d`.
Thanks.
