### ISSUE TITLE
Regarding the Wit dataset

### ISSUE THREAD

**Issue by yuanjiayu1234** [rutgers-db/SeRF#2]
Hello, may I ask which files you used as the basic dataset and which files as the query dataset for the Wit dataset, and whether the image size in your search key was crawled by yourself

**Comment by ciuji** [comment]
Hi,

We use the 1 million sample `resnet_embeddings` of the `image_data_train` as the basic dataset, and use the samples of `image_data_test` as the query dataset. We crawl the image sizes by ourselves through the URL link `image_url` of the original embeddings. 
If you want, I can share a 1M sample of WIT with you, please reach me at chaoji.zuo@rutgers.edu

Thanks,
Chaoji
